import React from 'react';
import { ScrollView, Text, View } from 'react-native';
import tw from 'twrnc';

const PrivacyPolicy = () => {
    const textStyle = { color: 'black' }; // Custom style for text components without styles

    return (
        <ScrollView>
            <View style={{ paddingTop: 70, paddingLeft: 10, display: "flex", flexDirection: "column", gap: 10, backgroundColor: "white" }}>
                <Text style={[tw`text-2xl font-bold`, textStyle]}>Privacy Policy</Text>
                <Text style={textStyle}>Last updated: April 22, 2024</Text>
                <Text style={textStyle}>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</Text>
                <Text style={textStyle}>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</Text>
                <Text style={[tw`mt-2 text-blue-600 font-bold text-base`]}>Interpretation and Definitions</Text>
                <Text style={tw`text-blue-600`}>Interpretation</Text>
                <Text style={textStyle}>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</Text>
                <Text style={tw`text-blue-600`}>Definitions</Text>
                <Text style={textStyle}>For the purposes of this Privacy Policy:</Text>
                <Text style={textStyle}>Account means a unique account created for You to access our Service or parts of our Service.</Text>
                <Text style={textStyle}>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</Text>
                <Text style={textStyle}>Application refers to Chase Your Dreams India, the software program provided by the Company.</Text>
                <Text style={textStyle}>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Chase Your Dreams India Pvt Ltd, 12-7-124/6, G2, Sai Bhanu Enclave, New Mettuguda, Secunderabad, 500017..</Text>
                <Text style={textStyle}>Country refers to Telangana, India</Text>
                <Text style={textStyle}>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</Text>
                <Text style={textStyle}>Personal Data is any information that relates to an identified or identifiable individual.</Text>
                <Text style={textStyle}>Service refers to the Application.</Text>
                <Text style={textStyle}>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</Text>
                <Text style={textStyle}>Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.</Text>
                <Text style={textStyle}>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Text>
                <Text style={textStyle}>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Text>
                <Text style={[tw`text-blue-700`]}>Collecting and Using Your Personal Data</Text>
                <Text style={[tw`text-blue-700`]}>Types of Data Collected</Text>
            </View>
        </ScrollView>
    );
};

export default PrivacyPolicy;
